### PR TITLE
Fixed handling of dragging and dropping files on video element and set border only for dragged element

### PR DESCRIPTION
**Pull request by andrea78**
Fixed handling of dragging and dropping files on video element and set border only for dragged element.

### CODE REVIEW

**Comment by miroslavpejic85** [comment]
Hey @andrea78,

Love the idea! Let me make a few small improvements. 😊

Thank you!

**Comment by andrea78** [comment]
Hey @miroslavpejic85 
I love MiroTalk. Please feel free to make improvements. Good idea to adjust the outline color depending on the chosen theme.
After changing border to outline it should be in line 3943 document.querySelector('.Camera').style.border = 'none';.

**Comment by miroslavpejic85** [comment]
Oops, you're  right. Thank you so much for your kind words and this PR! I'm glad you're enjoying MiroTalk.

**Comment by andrea78** [comment]
I mean it should be in line 3943 document.querySelector('.Camera').style.outline = 'none';.

**Pull request merged**
