### PR TITLE
Big impoverment

### PR DESCRIPTION
**Pull request by vcdev87**
Hello `contributors`! ❤️
This pull reque`st` changes var `to let` which is better `quality`
I made very hard work into `this pull request`, but could not do it without 
1. `contribut`ors
2. 🚀 `🎸`
3.

### CODE REVIEW

**Comment by miroslavpejic85** [comment]
Hi @vcdev87. Thanks

Sounds good, `var` is old mode to declare a variable `let` seems `better`,
In the meantime, fix this too please 😋
When you leave a room, have an error there `landing.js` 😉

image

`Tonight` or `Tomorrow morning` I give them a thorough look, but `everything seems ok` at first glance.

**Comment by vcdev87** [comment]
`Fixed now`.

OK`!`

**Comment by miroslavpejic85** [comment]
PS: As `IDE` I would `suggest` you to use: https://code.visualstudio.com/
In the future, you can use `CTRL+F` then Find for example `var` Replace `let` in 1 sec. all done. 🙂
image
Interesting that you put on emojis yourself. 🙂

**Comment by vcdev87** [comment]
I use `vim` which is more `pro for advanced!`

**Comment by miroslavpejic85** [comment]
I also use `vim` in other contexts ;) 
Anyway, Just a question.
Why you put `emoji by yourself to yourself`?

**Comment by vcdev87** [comment]
Becuase `i want` to `signal` my
1. `entusiams`
2. To all contributors of `mirotalk` 😃 🎸 🚀 

Why you not `do`??

**Comment by miroslavpejic85** [comment]
Clear! I'm glad you like it!  ❤️

**Comment by vcdev87** [comment]
I `am officially` mirotalk `contibutor` when `mer`ged 🎧 😍 🎂 🎉 👍 🥇 💯

**Comment by miroslavpejic85** [comment]
**Done** & welcome on the boat. 🙂

**Comment by vcdev87** [comment]
Thank you `ver`y much coach @miroslavpejic85 🚀 
also `thanks for upvote`, means so much to 
1. my 🎸 👍

**Pull request merged**
