### PR TITLE
Adjust class to improve background images

### PR DESCRIPTION
**Pull request by l4rm4nd**
Hi @miroslavpejic85,

the current background images look a bit off. Especially when browsed with an ultrawide monitor.

I suggest a simple fix by switching to another class that utilizes a more fitting and professional background image.

### Current background

image

### Adjusted background

image

### CODE REVIEW

**Comment by miroslavpejic85** [comment]
Hi @l4rm4nd,

Thanks for pointing this out, but I'd like to keep the current image. 

> the current background images look a bit off. Especially when browsed with an ultrawide monitor.

Could you please check now if it displays correctly? 

Thank you!

**Comment by l4rm4nd** [comment]
It got even worse.

image

**Comment by miroslavpejic85** [comment]
Now it should be ok.

**Comment by l4rm4nd** [comment]
Yep, background adjusts to the width dynamically.

**Pull request closed without merging**
