### PR TITLE
Some styling changes, Hope you like it!

### PR DESCRIPTION
**Pull request by Jaideep25**
Hi @miroslavpejic85 ! I tried to do some styling changes, Hope you like it!!

### CODE REVIEW

**Comment by miroslavpejic85** [comment]
Hey @Jaideep25 Thanks for the pr, imho they are a little too big button and flashy :) could be invasive for small screen phones. The video-audio status imho is important to be seen when it's disabled and actually is ok and red color is good visible. What you think for this solution for now? 
https://github.com/miroslavpejic85/mirotalk/commit/9a1849f4739257026b92f0e1400c00eb5a8ac7a1
I added on hover the green color, if someone have strong white background.
We can improve it later ;) 
As for mirotalk (lowercase) instead of Mirotalk (uppercase) I had put it on purpose. 
Do you say it's wrong?

**Comment by Jaideep25** [comment]
Hey @miroslavpejic85 , actually in some places Mirotalk looks more cool than mirotalk so just thought abt that!, and about the small screen phones, I made my browser small and checked, it, it was going cool, just sending a pic of it!
image

**Comment by miroslavpejic85** [comment]
@Jaideep25 Try now the new status menù on top. Like left buttons on mouse move it's shown if hidden, i think is little better and less invasive now. Let's me know if you like it?

**Comment by Jaideep25** [comment]
Ok sir! Thank you! ;)

**Pull request merged**
