### PR TITLE
Webcam disabling when video button is turned off

### LINKED ISSUE #152: Disabling video does not block access to the webcam
### Describe the bug

If a user decides to disable his video feed of the webcam, the webcam is still active or accessible by MiroTalk. This is a privacy issue, as the webcam should not be accessible as it was disabled by the user as an active choice. 

Also the status lights of webcams will continue to blink or breathe, which gives doubts about privacy.

### To Reproduce

1. Log into a web meeting with an enabled webcam
2. Disbable the web cam or video feed by hitting the respective button in the frontend
3. Although the video feed is not streamed anymore to participants, the webcam is still accessed and enabled in browser by MiroTalk. The status light, if available, blinks or breaths .. indicating a still ongoing access to the webcam.

### Expected behavior

If a user stops the webcam video, the webcam should not be accessed or be enabled anymore.

### PR DESCRIPTION
**Pull request by HariKrishna-28**
Fixes #152 

Fixes the issue by adding a function that disables the tracks that gets called when `myVideoStatus` is false

### CODE REVIEW

**Comment by HariKrishna-28** [comment]
Hello @miroslavpejic85! I have made the necessary changes as you've asked and please let me know if something needs to be changed.

Thank you and have a good day!

**Comment by miroslavpejic85** [comment]
> Hello @miroslavpejic85! I have made the necessary changes as you've asked and please let me know if something needs to be changed.
> 
> Thank you and have a good day!

Hi, As previously mentioned, it is imperative that we conduct further testing to ensure that everything is functioning optimally. If you have time to delve deeper into the project and address the issue, that would be greatly appreciated. However, if your schedule does not permit it at the moment, I am prepared to tackle it when I have more availability. 
Thank you for your understanding.

**Comment by miroslavpejic85** [comment]
> For example, when you share your screen and then press stop sharing screen button, it doesn't seem to bounce back to  the camera. It could be a side effect of the change made and so on....

[Fixed in master](https://github.com/miroslavpejic85/mirotalk/commit/4465051d365634b68586c6442684b1c5dc0c0e73), not related to this changes.

**Comment by miroslavpejic85** [comment]
Check out the updated snippet, please merge the branch with the latest Mirotalk master. Try some thorough cross-testing, but if you happen to come across any issues, please don't hesitate to get in touch with me. 
From what I quickly tested, the LED light seems to turn off correctly when the track video is stopped and vice versa, but everything else needs to be tested if it doesn't break something....
Thank you and I wish you a fantastic day!

**Comment by miroslavpejic85** [comment]
I'm going to close this for now as we need to review the code. There have been some significant changes, and I'd appreciate it if you could send me an updated PR. Thank you so much for your help and understanding. Your contributions are greatly appreciated!

**Pull request closed without merging**
