### PR TITLE
added live caption features

### PR DESCRIPTION
**Pull request by anshuman61**

### CODE REVIEW

**Comment by anshuman61** [comment]
For live text transcription and captioning

**Comment by miroslavpejic85** [comment]
Hello @anshuman61, 

Thanks for the PR, I'll check out as soon as I can. 
So the idea is to have a form that captures everything that is said in a conference in text format right? 
A kind of audio recording transformed into text.

I was wondering why someone must have the need to save what is said in text format, we already have the recording (audio/video/screen) for that and the chat. What do you think about it, what are the benefits? 

Another idea came to my mind how to take advantage of this fantastic function that you proposed to me.
We can use webkitSpeechRecognition to give voice commands to MiroTalk like:

- Start/Stop screen
- Start/Stop audio
- Start/Stop video
- and so on :)

A kind of Alexa - Siri integrated into MiroTalk! (I could open a task for this)

**Comment by anshuman61** [comment]
With this, I have completed the entire functioning of live captioning. This will be helpful for students to take notes on live classes. Also if someone wants to note something on a running meeting. Yeah as you suggested previously we can also made something like Alexa or Siri for this project

**Comment by miroslavpejic85** [comment]
Hello @anshuman61, 

I'm glad you like it, It can be improved, and thank you for the PR.

I improve it a little bit, mainly:

- Data it's sent through Datagram Transport Layer Security (DTLS) safer, not pass through signaling-server.
- The speech recognition is activated by the user itself (privacy).
- Improved the UI and added a sound when receiving speech transcription.
- If the browser does not support webkitSpeechRecognition, the button is not shown at all : https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API#browser_compatibility.
- Removed unused files.
- Execute `npm run lint` before pushing.

**Review by anshuman61 — COMMENTED** [review]
Seems pretty clear. Sorry for the unusual files as I am also thinking of adding a UI feature to show the user when one peer is talking with some mic-level indicator(volume_meter.js). I will take care of those things in future contributions.

**Comment by miroslavpejic85** [comment]
Yeah, that would be a great feature :) Thanks a lot, and now you're on the contributor list!

**Comment by anshuman61** [comment]
Working on the same.  Feeling glad to be a contributor 😊😊😊😊.

**Pull request merged**
