### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by l4rm4nd**
Hi @miroslavpejic85,

I've played a bit with your Dockerfile.

I think it is a bit unnecessary that users have to download your repository data such as /app and /public in order to run the Mirotalk container. I would leave this to power users if they want to adjust the frontend (html, css and stuff) to their liking.

Most people though should be fine by just running your container image that provides all latest data.

If power users want to adjust the container data, they can simply bind mount their adjusted data into the container just fine.

For example by doing the following:

````
# start the regular container image as usual
docker run -d -p 3000:3000 --name mirotalk mirotalk:latest

# then copy the container data onto the docker host server
docker cp mirotalk:/src /my/prefered/path/to/store/mirotalk/data

# now we can adjust all files at /my/prefered/path/to/store/mirotalk/data/src to our liking

# after that, we remove the old container and restart it by bind mounting our data from docker host into container
docker container rm mirotalk --force
docker run -d -p 3000:3000 -v /my/prefered/path/to/store/mirotalk/data/src:/src --name mirotalk mirotalk:latest
````
Or they just clone your repo and directly bind mount /app and /public into the container paths /src/app and /src/public. Would be easier I guess.

Note that you may want to provide a production `.env` with hardened presets. Especially strong default API secrets if users forget to bring their own .env file.

### CODE REVIEW

**Comment by l4rm4nd** [comment]
I've forked your repository and added some GitHub Actions to automatically build the Docker image.

https://github.com/l4rm4nd/mirotalk

Feel free to use [my Docker image](https://hub.docker.com/repository/docker/l4rm4nd/mirotalk/general
) on DockerHub to verify that everything is working as intended:

````
docker run -d -p 3000:3000 --name mirotalk l4rm4nd/mirotalk:latest
````
Note though that I've adjusted some frontend stuff to my liking. In production, I'll just bind mount my hardened `.env` file into the container. Example compose file would be:

````
version: '3.7'

services:
  mirotalk:
    image: l4rm4nd/mirotalk:latest
    restart: unless-stopped
    container_name: mirotalk
    hostname: mirotalk
    ports:
      - 3000:3000 # WEB UI
    volumes:
      - .env:/src/.env:ro
````

**Comment by miroslavpejic85** [comment]
Hey @l4rm4nd, 

Thank you very much for all this! 

How about renaming `docker-compose.yml` to `docker-compose.template.yml`, then anyone can edit their own docker-compose to suit their needs, as in the SFU version.

And I add in the procedure simply

```bash
# Copy docker-compose.template.yml in docker-compose.yml and edit it if needed
$ cp docker-compose.template.yml docker-compose.yml
```

So `docker-compose.yml` in your case will be

```yaml
version: '3.7'

services:
   myrotalk:
     image: l4rm4nd/mirotalk:latest
     restart: unless-stopped
     container_name: mirotalk
     hostname: mirotalk
     ports:
       - 3000:3000 # WEB UI
     volumes:
       - .env:/src/.env:ro
```

in my case i want to keep the volume mount on app & public that is useful for me for test and debug in real time.

```yaml
version: '3'

services:
     myrotalk:
         image: mirotalk/p2p:latest
         builds:
             context: .
             dockerfile: Dockerfile
         container_name: mirotalk
         hostname: mirotalk
         volumes:
             - .env:/src/.env:ro
             - ./app/:/src/app/:ro
             - ./public/:/src/public/:ro
         restart: unless-stopped
         ports:
             - '3000:3000'
```

Doing so with git pull your docker-compose.yml will never be overwritten and anyone can edit it at will according to their needs, without being forced to use the current ones in the docekr-compose.yml as default  :slightly_smiling_face:

**Comment by l4rm4nd** [comment]
> How about renaming

Hey @miroslavpejic85, 

providing a `docker-compose.yml` file in your repository would be good but does not really target the actual problem of people having to first download your `/app` and `/public` folders before being able to run the container correctly.

For development purposes or power users that want to use their adjusted /app and /public files you can just bind mount the folders into the container. However, by using my provided `Dockerfile`, this would be now optional. Currently, bind mounting the /app and /public folders is mandatory in order to run your container.

### Problem description

The actual problem waas mentioned on reddit [here](https://www.reddit.com/r/selfhosted/comments/11kt8zi/comment/jbb0ibq/?utm_source=share&utm_medium=web2x&context=3).

Basically, most people just want to use an already built container image by the maintainer. In your case, people just want to use `mirotalk/p2p:latest` and run the container. However, currently, people first have to download or clone your repository and then bind mount the /app and /public directories in the container. Not a big problem itself but now comes the interesting part.

A lot of people, including myself, are using another Docker container like Watchtower to monitor Docker images for new updates. So if you push new stuff into the repo and build a new docker image, the Watchtower container will notify us end users that the currently used image is outdated. We can therefore just download the newest image and redeploy the container and are up2date on the latest Docker image provided by you. Watchtower can do this process even automatically. Now comes the issue many are facing. By just downloading the latest `mirotalk/p2p:latest` from DockerHub, were are actually not on latest because we still have to bind mount /app and /public into the container. These directories are likely outdated too .. so we would also have to do a `git pull` beforehand to be really up2date. This is unnecessary for most people, as they just want to your provided container, which should hold all relevant repo data.

So by using my adjusted Dockerfile, we gain two options:

### Regular users - no adjustments

Regular users can just use Docker run or a simple compose file to run your container. 

For example:

````
docker run -d -p 3000:3000 --name mirotalk mirotalk:latest
````
The container service will just work and be available on http://127.0.0.1:3000 for testing. 

If you like Mirotalk and want to use productively, you would bind mount your customized .env file into the container and that's it. No need for `git pull` or any fancy measures to keep the /app and /public dirs up2date.

````
docker run -d -p 3000:3000 -v .env:/src/.env:ro --name mirotalk mirotalk:latest
````

Using this, people can just fetch your latest Docker image from Dockerhub (either manually or via watchtower) and do not have to also issue a `git pull` or anything to fetch the latest /app and /public files.

### Development - Miro wants to test things

As maintainer, you may want to adjust things and test them out. No problem with my Dockerfile. Just bind mount your data into the container as usual. Your host data like `.env` or `./app` and `./public` will overlay the container data in /src. So your started container will use your provided files instead of the default ones from the GitHub repo.

````
docker run -d -p 3000:3000 -v .env:/src/.env:ro -v ./app/:/src/app/:ro -v ./public/:/src/public/:ro --name mirotalk mirotalk:latest
````

**Comment by ovizii** [comment]
@l4rm4nd thanks for perfectly explaining - I should copy and save this explanation as I often need it ;-)

**Comment by miroslavpejic85** [comment]
Hey @l4rm4nd,

Love your explanation! Thank you :)

> providing a docker-compose.yml file in your repository would be good but does not really target the actual problem of people having to first download your /app and /public folders before being able to run the container correctly.

I'm agree with you, for that i thinking to create `docker-compose.template.yml` as the following:

```yml
version: '3.7'

services:
   myrotalk:
     image: mirotalk/p2p:latest
     restart: unless-stopped
     container_name: mirotalk
     hostname: mirotalk
     ports:
       - 3000:3000 # WEB UI
     volumes:
       - .env:/src/.env:ro
```

So anyone can decide if running mirotlak with docker-compose or docker like:

```bash
docker run -d -p 3000:3000 --name mirotalk mirotalk:latest
```

In this way, bind mounting the /app and /public folders is NOT mandatory in order to run the container. And the people not have to download or clone the repository and then bind mount the /app and /public directories in the container and not have to do a git pull beforehand to be really up2date. 

Tell me am I wrong?

And of course this PR can be merged as well!

**Comment by l4rm4nd** [comment]
> bind mounting the /app and /public folders is NOT mandatory in order to run the container

Oh, I just tried it again and you are right. It is not mandatory anymore.

The first time I tried your project I had to specifically bind mount the /app and /public dir. Now the container works without having to.

**Comment by miroslavpejic85** [comment]
> Now the container works without having to bind mount anything

Yeah, that is what i want to said :) The 2 volume mount i put on docker-compose are not mandatory, the official image has all the project inside, for that i will create a `docker-compose.template.yaml` which then anyone can copy it and modify it at will, or use docker to launch it directly as weel. 

for my usage case the `docker-compose.yaml` will be

```yaml
version: '3'

services:
     myrotalk:
         image: mirotalk/p2p:latest
         builds:
             context: .
             dockerfile: Dockerfile
         container_name: mirotalk
         hostname: mirotalk
         volumes:
             - .env:/src/.env:ro
             - ./app/:/src/app/:ro
             - ./public/:/src/public/:ro
         restart: unless-stopped
         ports:
             - '3000:3000'
```
Or i can run it directly like you said with `docker`

```bash
docker run -d -p 3000:3000 -v .env:/src/.env:ro -v ./app/:/src/app/:ro -v ./public/:/src/public/:ro --name mirotalk mirotalk:latest
```

**Comment by ovizii** [comment]
Hey, that is cool. Here's how I saw other projects commenting inside their docker-compose template files which seems to make sense to me:

```
         volumes:
             - .env:/src/.env:ro
# these 2 volumes are not mandatory, uncomment if you want to customize them
#             - ./app/:/src/app/:ro
#             - ./public/:/src/public/:ro
```

Having some comments inside is awesome, you can even add links to some docs if you like so while editing the compose file one can click them and read up on the subject.

Anyway, just a suggestion you figure out what is best for your project.

Thanks for your openness and responsiveness though!

**Comment by miroslavpejic85** [comment]
> Having some comments inside is awesome, you can even add links to some docs if you like so while editing the compose file one can click them and read up on the subject.

Yes, I like the idea. Do you want to do a PR for this? Or I'll edit on the fly, as you prefer ;) 

> Thanks for your openness and responsiveness though!

It's a pleasure, thanks to you too for your interest and for your contribution!

**Comment by ovizii** [comment]
> Yes, I like the idea. Do you want to do a PR for this? Or I'll edit on the fly, as you prefer ;)
Nah, no need for a PR, go right ahead as you like :-)

**Pull request closed without merging**
