### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by Jaideep25**
Added docker dependency! And if you don't mind can I send a pr of yarn?

### CODE REVIEW

**Comment by miroslavpejic85** [comment]
Hi @Jaideep25 :) 
Thanks for the `PR` but I think this addiction is unnecessary. 👀
If someone want to use `mirotalk` on `docker`, just follow this part already `done`: https://github.com/miroslavpejic85/mirotalk#docker

**Comment by Jaideep25** [comment]
Ok! But when I downloaded docker n did all that this dependency came up so thought of sharing 😊, btw shld I give a pr of yarn or not needed?

**Comment by miroslavpejic85** [comment]
And I not like `this part` when put this `dependency`
```logs
14 vulnerabilities (7 moderate, 7 high)
```
without
```logs
found 0 vulnerabilities
```

**Comment by Jaideep25** [comment]
This is common actually 😅

**Comment by miroslavpejic85** [comment]
So how about not adding this addiction for now? 😅

**Comment by Jaideep25** [comment]
Sure!

**Pull request closed without merging**
