### PR TITLE
add kubernetes deployment files

### PR DESCRIPTION
**Pull request by bmanojlovic**
as stated in subject these files represent files required to succesfully deploy mirotalk on kubernetes cluster.

if you need some more information to be provided already in README.md just ask :)

### CODE REVIEW

**Comment by bmanojlovic** [comment]
please wait with merge until i fix few kinks

**Comment by bmanojlovic** [comment]
should work now just fine

**Comment by miroslavpejic85** [comment]
Hello @bmanojlovic,

Thank you so much for the PR! As P2P (connection between browsers) I think not need to scale more instances, hovewer it can be useful if someone want to try it on k8s!

In the README change `make deployment` to `make deploy`

```
miroslavpejic@MacBook-Pro-di-Miroslav ~/g/c/k/m/kubernetes (kubernetes)> make deployment
make: *** No rule to make target `deployment'.  Stop.
```

PS: Is there a way to run it on Local k8s using [minikube](https://minikube.sigs.k8s.io/docs/start/)? 
If so need to changes something in the current yaml?

Thank you!

**Comment by bmanojlovic** [comment]
to be  honest i do not have minikube - in sense i do not use it, but yes you can use it just fine in minikube using DNS providers such as nip.io that will map your local dev IP to domain such as `192.168.20.1` to for example `192-168-20-1.nip.io`
in which case you can in p2p-ingress.yaml use `p2p.192-168-20-1.nip.io`

cert-manager.io is again there to provide SSL certificate if you need it with use of step-ca as a provider (which is too much of this comment section :) )

If you need more information how to do it just fire comment

**Comment by bmanojlovic** [comment]
I have just tested minikube and i can say it does not work, not because of my "code" but rather minikube is a bit picky and how it implements ingress object (nginx ingress + requirement for nodeport), 
will look to create minikube alternative now and try that

**Comment by bmanojlovic** [comment]
please test with steps outlined in README.md for me it is only partially working...
So if you can install k3s (testing primarily in it and using it as production kubernetes to be honest for all projects) 
install cert-manager (or before running make prepare move p2p-cert.yaml somewhere else) and try code in k3s cluster (or any other "normal" kubernetes cluster

**Comment by miroslavpejic85** [comment]
Ok I found a way to test in localhost without ssl:

1. make
2. make prepare
3. comment the `p2p-cert` part on `output/mirotalk-k8s.yaml`

```
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: localhost-tls
# spec:
#   duration: 2880h # 180d
#   renewBefore: 360h # 15d
#   commonName: localhost 
#   dnsNames:
#   - localhost 
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt
#   secretName: localhost-tls
```
4. make deploy
5. Check the `service` and set a `port-forwarding`:

```bash
$ miroslavpejic@MacBook-Pro-di-Miroslav ~> kubectl get svc
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP    6h13m
p2p          ClusterIP   10.96.69.238   <none>        3000/TCP   19s
miroslavpejic@MacBook-Pro-di-Miroslav ~> kubectl port-forward svc/p2p 3000:3000
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
```

Open in browser: http://localhost:3000

**Comment by bmanojlovic** [comment]
yes that is rather easy to do, but that is just a part of it how it is supposed to be exposed in kubernetes.
Idea is that if you add ingress it should expose it to "real ip" of minikube cluster and ports 80 and 443 should work just fine.

**Comment by bmanojlovic** [comment]
Minikube is VERY limiting in what you can do with it (it does work fine  just very limiting in default setup).
I can guide you over mirotalk session (😀) if you would like to try installing [k3s](https://k3s.io) and necessary things to make initial setup easy. What you need for start is some kind of virtualization - assumption is that you have [Virtualbox](https://www.virtualbox.org/) if nothing else and that you can bridge its network to your local LAN and it would receive "external" IP address from your home router.

**Comment by miroslavpejic85** [comment]
Hi @bmanojlovic, 

I know k8s, I wrote down [some notes](https://github.com/miroslavpejic85/kubernetes-k8s) years ago on how to set up a master-node kubernetes cluster.
k3s is new to me but it's very nice and fast to set up a kubernetes. 
I Installed it on VM - Ubuntu 22.04.2 LTS server and tried your initial setup and everything seems ok. 
For me you can delete the minkube part, update the readme, change a bit Makefile and adding `make delete`


Make


Check if the yamls are [indented well](https://codebeautify.org/yaml-beautifier#
), or run the `npm run lint` in the project folder, which use `prettier`.

As i said, `being P2P`, it not need to be scaled, but i can accept this PR in case someone want to play with it on kubernetes.

Thank you for your time!

**Comment by bmanojlovic** [comment]
(added delete: target and remove minikube)

SFU was next target to be honest, just for me p2p was initial target. 
FYI most of boilerplate you can generate from docker-compose.yaml files with use of [kompose](https://kompose.io/),
in any case I will try to do it in near future (as i would prefer to have full SFU rather than to use p2p and third party TURN server)

**Comment by miroslavpejic85** [comment]
Thank you, merged.

**Pull request merged**
