### PR TITLE
`Docker build important` fix `of contribrutors`

### PR DESCRIPTION
**Pull request by vcdev87**
`I fix `build docker `readmme` description 
with
1. `this pull` 
2. `request`.
`  2.2:` Alone we can do so little, to`gether we` can do so much.

### CODE REVIEW

**Comment by mmguero** [comment]
This is not a good commit, because it will break automation (ie., building from a git clone without .env existing). We do not want to be copying user-specific .env files into the dockerfile, it is a security risk. It should be mapped in at runtime via a bind mount instead.

**Comment by miroslavpejic85** [comment]
Hi @mmguero Thanks for the comment, 
@vcdev87 thanks anyway for the effort.

**Comment by vcdev87** [comment]
No `need `to be `RUDE` @mmguero !

in readme `file` in docker `section` it says
1: cp .env.template .env
2. docker compose up

But dockerfile is copying in .env.template and not `.env` which is the `modified file.`
SO maybe remove `cp .env.template .env` from README; and it will be correct!

**Comment by mmguero** [comment]
It wasn't my intention to be rude.

Those two things you mentioned (the README and the Dockerfile) are totally different things.

The Dockerfile contains instructions for building the docker image, which should not contain sensitive or user-specific information in its env file. We copy the template into the docker image just for reference.

The README talks about setting up your local environment: copy .env.template to .env, edit .env, then use Docker a volume bind to mount your local .env file into the docker image over top of the template one.

Both the Dockerfile and the README are correct.

**Pull request closed without merging**
