### PR TITLE
Document Picture-in-Picture support

### PR DESCRIPTION
**Pull request by endaquigley**
Room for improvement but this adds basic Document Picture-in-Picture support to the app.

https://github.com/miroslavpejic85/mirotalk/assets/753515/6d6c5916-5730-4a5f-b335-2259eeab23a8

### CODE REVIEW

**Comment by miroslavpejic85** [comment]
Hey @endaquigley, I just wanted to say a big thank you for your contribution – I absolutely love it! 😍 
Let me know if you still need to make any changes, IMHO seems very good!
Are you registered for the [hacktoberfest](https://hacktoberfest.com/)? 
If so, this contribution will be taken (counted) as valid.

**Comment by endaquigley** [comment]
Hey @miroslavpejic85, no problem - glad I could contribute to this project 🙌

I made a few small tweaks earlier, but I'm done for now.

**Comment by miroslavpejic85** [comment]
I'll get started on the merge right away! If you'd like, You can also add the same functionality to the [MiroTalk SFU](https://github.com/miroslavpejic85/mirotalksfu) version. Thanks once again, and I'm thrilled to have you as a contributor! 😎

**Comment by miroslavpejic85** [comment]
close #163

**Pull request merged**
